/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author JordenZertuche
 */
public class Calc extends javax.swing.JFrame {

    //basis for calcluator
    Double Num1;
    Double Num2;
    String Operator;
    Double Math;
    boolean StartNumber2;
    
    
            
            
    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextResult1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JZertuche_Calculator");

        jTextResult1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextResult1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton10.setText("0");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton11.setText(".");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton12.setText("=");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton13.setText("/");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton14.setText("x");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton16.setText("+");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton17.setText("AC");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton18.setText("+/-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextResult1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String result;
        
        //method
        //constructor
        if (Num1 == null)
                {
                   Num1 = Double.parseDouble(jTextResult1.getText()); 
                   StartNumber2 = true;
                }
        else if (Num2 == null)
        {
            Num2 = Double.parseDouble(jTextResult1.getText());
            
            if(Operator == "+")
            {
                Math = Num1 + Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "-")
            {
                Math = Num1 - Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "*")
            {
                Math = Num1 * Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "/")
            {
                Math = Num1 / Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
           
        
        }
                Operator = "/";
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton1.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton1.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton2.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton2.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton3.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton3.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton4.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton4.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton5.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton5.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton6.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton6.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton7.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton7.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton8.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton8.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton9.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton9.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton10.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton10.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(StartNumber2 == true)
        {
            String BtnValue = jButton11.getText();
            jTextResult1.setText(BtnValue);
            StartNumber2 = false;
        }
        else
        {
            String BtnValue = jTextResult1.getText() + jButton11.getText();
            jTextResult1.setText(BtnValue);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jTextResult1.setText("");
        Num1 = null;
        Num2 = null;
        StartNumber2 = false;
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        double Sign = Double.parseDouble(String.valueOf(jTextResult1.getText()));
        Sign = (-1)*Sign;
        jTextResult1.setText(String.valueOf(Sign));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
        String result;
        System.out.println(String.valueOf(StartNumber2));
        System.out.println(String.valueOf(Num1));
        System.out.println(String.valueOf(Num2));
                
        if (Num1 == null)
                {
                   Num1 = Double.parseDouble(jTextResult1.getText()); 
                   System.out.println(String.valueOf(Num1));
                   StartNumber2 = true;
                }
        else if (Num2 == null)
        {
            Num2 = Double.parseDouble(jTextResult1.getText());
            
            System.out.println(String.valueOf(Num1));
            System.out.println(String.valueOf(Num2));
            if(Operator == "+")
            {
                Math = Num1 + Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "-")
            {
                Math = Num1 - Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "*")
            {
                Math = Num1 * Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "/")
            {
                Math = Num1 / Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }

            
        
        }
                Operator = "+";
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        //calculation method for solving and creating
        String result;
        
        
        if (Num1 == null)
                {
                   Num1 = Double.parseDouble(jTextResult1.getText()); 
                   StartNumber2 = true;
                }
        else if (Num2 == null)
        {
            Num2 = Double.parseDouble(jTextResult1.getText());
            
            if(Operator == "+")
            {
                Math = Num1 + Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "-")
            {
                Math = Num1 - Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "*")
            {
                Math = Num1 * Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "/")
            {
                Math = Num1 / Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            
        }
                Operator = "-";
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String result;
        
        //Extra precentage calculator
        if (Num1 == null)
                {
                   Num1 = Double.parseDouble(jTextResult1.getText()); 
                   StartNumber2 = true;
                }
        else if (Num2 == null)
        {
            Num2 = Double.parseDouble(jTextResult1.getText());
            
            if(Operator == "+")
            {
                Math = Num1 + Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "-")
            {
                Math = Num1 - Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "*")
            {
                Math = Num1 * Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "/")
            {
                Math = Num1 / Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            
        
        }
                Operator = "*";
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String result;
        
        if (Num1 == null)
                {
                   Num1 = Double.parseDouble(jTextResult1.getText()); 
                   StartNumber2 = true;
                }
        else if (Num2 == null)
        {
            Num2 = Double.parseDouble(jTextResult1.getText());
            
            if(Operator == "+")
            {
                Math = Num1 + Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "-")
            {
                Math = Num1 - Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "*")
            {
                Math = Num1 * Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            else if (Operator == "/")
            {
                Math = Num1 / Num2;
                result = String.format("%.0f",Math);
                jTextResult1.setText(result);
                Num1 = Math;
                Num2 = null;
                StartNumber2 = true;
            }
            
        }
        Operator = "";
        Num1 = null;
        Num2 = null;
        StartNumber2 = false;
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }
//buttons and button declaration
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextResult1;
    // End of variables declaration//GEN-END:variables
}
